apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone-eks-cluster
  region: us-west-2

nodeGroups:
  - name: standard-workers
    instanceType: m5.xlarge
    desiredCapacity: 2
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
      publicKeyPath: ~/.ssh/isa56kaws.pub
