
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-web
  labels:
    app: capstone-web
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-web
    spec:
      containers:
      - name: cdoe-capstone-proj
        image: 645851037944.dkr.ecr.us-west-2.amazonaws.com/cdoe-capstone-proj:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "64Mi"
            cpu: "250m"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP